# Generated by Django 3.0.5 on 2020-04-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('F', 'Fundacja'), ('OP', 'Organizacja pozarządowa'), ('ZL', 'Zbiórka lokalna')], default='Fundacja', max_length=2),
        ),
    ]
