# Generated by Django 3.0.5 on 2020-05-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_donation_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_update',
            field=models.DateField(auto_now=True),
        ),
    ]
